[package]
name = "burn_api_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.15.0", features = ["fusion", "ndarray", "wgpu"] }
zarrs = "0.18.0"
zarrs_filesystem = "0.2.0"

[dev-dependencies]
backend_tests_derive = { path = "./backend_tests_derive" }
